### ISSUE TITLE
FEATREQ - Schedule Page

### ISSUE THREAD

**Issue by agiveygives** [MST-Game-Development/website#13]
**Is your feature request related to a problem? Please describe.**
I want an embedded Calendar to show all the club's events events.

**Describe the solution you'd like**
There should be a Schedule page that has a Google calendar for me to view event times, titles, descriptions, and add them to my calendar.

**Describe alternatives you've considered**
We could has out our own calendar component, but Google Calendar will probably be easier, and it would allow leadership to manage it from the Google Calendar app on their phone.

**Comment by ekelly14** [comment]
I currently am working on getting a concept for implementing google calendar into the schedule page. Will be following up with a breakdown when I get things hammered out
